const sampleCountries = [
  {
    Name: "Malta",
    Population: 525285,
    Region: "Europe",
    Capital: ["Valletta"],
    Flag_PNG: "https://flagcdn.com/w320/mt.png",
  },
  {
    Name: "Sweden",
    Population: 10353442,
    Region: "Europe",
    Capital: ["Stockholm"],
    Flag_PNG: "https://flagcdn.com/w320/se.png",
  },
  {
    Name: "New Caledonia",
    Population: 271960,
    Region: "Oceania",
    Capital: ["Nouméa"],
    Flag_PNG: "https://flagcdn.com/w320/nc.png",
  },
  {
    Name: "Burkina Faso",
    Population: 20903278,
    Region: "Africa",
    Capital: ["Ouagadougou"],
    Flag_PNG: "https://flagcdn.com/w320/bf.png",
  },
  {
    Name: "Bosnia and Herzegovina",
    Population: 3280815,
    Region: "Europe",
    Capital: ["Sarajevo"],
    Flag_PNG: "https://flagcdn.com/w320/ba.png",
  },
  {
    Name: "Jordan",
    Population: 10203140,
    Region: "Asia",
    Capital: ["Amman"],
    Flag_PNG: "https://flagcdn.com/w320/jo.png",
  },
  {
    Name: "Puerto Rico",
    Population: 3194034,
    Region: "Americas",
    Capital: ["San Juan"],
    Flag_PNG: "https://flagcdn.com/w320/pr.png",
  },
  {
    Name: "Greenland",
    Population: 56367,
    Region: "Americas",
    Capital: ["Nuuk"],
    Flag_PNG: "https://flagcdn.com/w320/gl.png",
  },
  {
    Name: "Iran",
    Population: 83992953,
    Region: "Asia",
    Capital: ["Tehran"],
    Flag_PNG: "https://flagcdn.com/w320/ir.png",
  },
  {
    Name: "Lesotho",
    Population: 2142252,
    Region: "Africa",
    Capital: ["Maseru"],
    Flag_PNG: "https://flagcdn.com/w320/ls.png",
  },
  {
    Name: "Latvia",
    Population: 1901548,
    Region: "Europe",
    Capital: ["Riga"],
    Flag_PNG: "https://flagcdn.com/w320/lv.png",
  },
  {
    Name: "Madagascar",
    Population: 27691019,
    Region: "Africa",
    Capital: ["Antananarivo"],
    Flag_PNG: "https://flagcdn.com/w320/mg.png",
  },
  {
    Name: "Cyprus",
    Population: 1207361,
    Region: "Europe",
    Capital: ["Nicosia"],
    Flag_PNG: "https://flagcdn.com/w320/cy.png",
  },
  {
    Name: "Mauritius",
    Population: 1265740,
    Region: "Africa",
    Capital: ["Port Louis"],
    Flag_PNG: "https://flagcdn.com/w320/mu.png",
  },
  {
    Name: "Eswatini",
    Population: 1160164,
    Region: "Africa",
    Capital: ["Mbabane"],
    Flag_PNG: "https://flagcdn.com/w320/sz.png",
  },
  {
    Name: "Solomon Islands",
    Population: 686878,
    Region: "Oceania",
    Capital: ["Honiara"],
    Flag_PNG: "https://flagcdn.com/w320/sb.png",
  },
  {
    Name: "Austria",
    Population: 8917205,
    Region: "Europe",
    Capital: ["Vienna"],
    Flag_PNG: "https://flagcdn.com/w320/at.png",
  },
  {
    Name: "Vatican City",
    Population: 451,
    Region: "Europe",
    Capital: ["Vatican City"],
    Flag_PNG: "https://flagcdn.com/w320/va.png",
  },
  {
    Name: "Malawi",
    Population: 19129955,
    Region: "Africa",
    Capital: ["Lilongwe"],
    Flag_PNG: "https://flagcdn.com/w320/mw.png",
  },
  {
    Name: "Botswana",
    Population: 2351625,
    Region: "Africa",
    Capital: ["Gaborone"],
    Flag_PNG: "https://flagcdn.com/w320/bw.png",
  },
  {
    Name: "Djibouti",
    Population: 988002,
    Region: "Africa",
    Capital: ["Djibouti"],
    Flag_PNG: "https://flagcdn.com/w320/dj.png",
  },
  {
    Name: "Republic of the Congo",
    Population: 89561404,
    Region: "Africa",
    Capital: ["Brazzaville"],
    Flag_PNG: "https://flagcdn.com/w320/cg.png",
  },
  {
    Name: "Barbados",
    Population: 287371,
    Region: "Americas",
    Capital: ["Bridgetown"],
    Flag_PNG: "https://flagcdn.com/w320/bb.png",
  },
  {
    Name: "Sint Maarten",
    Population: 40812,
    Region: "Americas",
    Capital: ["Philipsburg"],
    Flag_PNG: "https://flagcdn.com/w320/sx.png",
  },
  {
    Name: "Rwanda",
    Population: 12952209,
    Region: "Africa",
    Capital: ["Kigali"],
    Flag_PNG: "https://flagcdn.com/w320/rw.png",
  },
  {
    Name: "Jersey",
    Population: 100800,
    Region: "Europe",
    Capital: ["Saint Helier"],
    Flag_PNG: "https://flagcdn.com/w320/je.png",
  },
  {
    Name: "Bouvet Island",
    Population: 0,
    Region: "Antarctic",
    Capital: undefined,
    Flag_PNG: "https://flagcdn.com/w320/bv.png",
  },
  {
    Name: "Yemen",
    Population: 29825968,
    Region: "Asia",
    Capital: ["Sana'a"],
    Flag_PNG: "https://flagcdn.com/w320/ye.png",
  },
  {
    Name: "Brazil",
    Population: 212559409,
    Region: "Americas",
    Capital: ["Brasília"],
    Flag_PNG: "https://flagcdn.com/w320/br.png",
  },
  {
    Name: "Algeria",
    Population: 510713,
    Region: "Africa",
    Capital: ["Algiers"],
    Flag_PNG: "https://flagcdn.com/w320/dz.png",
  },
  {
    Name: "Kazakhstan",
    Population: 18754440,
    Region: "Asia",
    Capital: ["Nur-Sultan"],
    Flag_PNG: "https://flagcdn.com/w320/kz.png",
  },
  {
    Name: "Saint Martin",
    Population: 38659,
    Region: "Americas",
    Capital: ["Marigot"],
    Flag_PNG: "https://flagcdn.com/w320/mf.png",
  },
  {
    Name: "Curaçao",
    Population: 155014,
    Region: "Americas",
    Capital: ["Willemstad"],
    Flag_PNG: "https://flagcdn.com/w320/cw.png",
  },
  {
    Name: "Fiji",
    Population: 896444,
    Region: "Oceania",
    Capital: ["Suva"],
    Flag_PNG: "https://flagcdn.com/w320/fj.png",
  },
  {
    Name: "Pakistan",
    Population: 220892331,
    Region: "Asia",
    Capital: ["Islamabad"],
    Flag_PNG: "https://flagcdn.com/w320/pk.png",
  },
  {
    Name: "South Georgia",
    Population: 30,
    Region: "Antarctic",
    Capital: ["King Edward Point"],
    Flag_PNG: "https://flagcdn.com/w320/gs.png",
  },
  {
    Name: "Georgia",
    Population: 3714000,
    Region: "Asia",
    Capital: ["Tbilisi"],
    Flag_PNG: "https://flagcdn.com/w320/ge.png",
  },
  {
    Name: "Namibia",
    Population: 2540916,
    Region: "Africa",
    Capital: ["Windhoek"],
    Flag_PNG: "https://flagcdn.com/w320/na.png",
  },
  {
    Name: "Guinea-Bissau",
    Population: 1967998,
    Region: "Africa",
    Capital: ["Bissau"],
    Flag_PNG: "https://flagcdn.com/w320/gw.png",
  },
  {
    Name: "Norway",
    Population: 5379475,
    Region: "Europe",
    Capital: ["Oslo"],
    Flag_PNG: "https://flagcdn.com/w320/no.png",
  },
  {
    Name: "Christmas Island",
    Population: 2072,
    Region: "Oceania",
    Capital: ["Flying Fish Cove"],
    Flag_PNG: "https://flagcdn.com/w320/cx.png",
  },
  {
    Name: "Liechtenstein",
    Population: 38137,
    Region: "Europe",
    Capital: ["Vaduz"],
    Flag_PNG: "https://flagcdn.com/w320/li.png",
  },
  {
    Name: "India",
    Population: 1380004385,
    Region: "Asia",
    Capital: ["New Delhi"],
    Flag_PNG: "https://flagcdn.com/w320/in.png",
  },
  {
    Name: "France",
    Population: 67391582,
    Region: "Europe",
    Capital: ["Paris"],
    Flag_PNG: "https://flagcdn.com/w320/fr.png",
  },
  {
    Name: "Hong Kong",
    Population: 7500700,
    Region: "Asia",
    Capital: ["City of Victoria"],
    Flag_PNG: "https://flagcdn.com/w320/hk.png",
  },
  {
    Name: "Anguilla",
    Population: 13452,
    Region: "Americas",
    Capital: ["The Valley"],
    Flag_PNG: "https://flagcdn.com/w320/ai.png",
  },
  {
    Name: "Colombia",
    Population: 50882884,
    Region: "Americas",
    Capital: ["Bogotá"],
    Flag_PNG: "https://flagcdn.com/w320/co.png",
  },
  {
    Name: "Iraq",
    Population: 40222503,
    Region: "Asia",
    Capital: ["Baghdad"],
    Flag_PNG: "https://flagcdn.com/w320/iq.png",
  },
  {
    Name: "Morocco",
    Population: 36910558,
    Region: "Africa",
    Capital: ["Rabat"],
    Flag_PNG: "https://flagcdn.com/w320/ma.png",
  },
  {
    Name: "Libya",
    Population: 6871287,
    Region: "Africa",
    Capital: ["Tripoli"],
    Flag_PNG: "https://flagcdn.com/w320/ly.png",
  },
  {
    Name: "Saint Lucia",
    Population: 183629,
    Region: "Americas",
    Capital: ["Castries"],
    Flag_PNG: "https://flagcdn.com/w320/lc.png",
  },
  {
    Name: "Marshall Islands",
    Population: 59194,
    Region: "Oceania",
    Capital: ["Majuro"],
    Flag_PNG: "https://flagcdn.com/w320/mh.png",
  },
  {
    Name: "Sierra Leone",
    Population: 7976985,
    Region: "Africa",
    Capital: ["Freetown"],
    Flag_PNG: "https://flagcdn.com/w320/sl.png",
  },
  {
    Name: "Cook Islands",
    Population: 18100,
    Region: "Oceania",
    Capital: ["Avarua"],
    Flag_PNG: "https://flagcdn.com/w320/ck.png",
  },
  {
    Name: "Croatia",
    Population: 4047200,
    Region: "Europe",
    Capital: ["Zagreb"],
    Flag_PNG: "https://flagcdn.com/w320/hr.png",
  },
  {
    Name: "Turkmenistan",
    Population: 6031187,
    Region: "Asia",
    Capital: ["Ashgabat"],
    Flag_PNG: "https://flagcdn.com/w320/tm.png",
  },
  {
    Name: "Bhutan",
    Population: 771612,
    Region: "Asia",
    Capital: ["Thimphu"],
    Flag_PNG: "https://flagcdn.com/w320/bt.png",
  },
  {
    Name: "United Kingdom",
    Population: 67215293,
    Region: "Europe",
    Capital: ["London"],
    Flag_PNG: "https://flagcdn.com/w320/gb.png",
  },
  {
    Name: "Monaco",
    Population: 39244,
    Region: "Europe",
    Capital: ["Monaco"],
    Flag_PNG: "https://flagcdn.com/w320/mc.png",
  },
  {
    Name: "Palau",
    Population: 18092,
    Region: "Oceania",
    Capital: ["Ngerulmud"],
    Flag_PNG: "https://flagcdn.com/w320/pw.png",
  },
  {
    Name: "Gabon",
    Population: 2225728,
    Region: "Africa",
    Capital: ["Libreville"],
    Flag_PNG: "https://flagcdn.com/w320/ga.png",
  },
  {
    Name: "Germany",
    Population: 83240525,
    Region: "Europe",
    Capital: ["Berlin"],
    Flag_PNG: "https://flagcdn.com/w320/de.png",
  },
  {
    Name: "Japan",
    Population: 125836021,
    Region: "Asia",
    Capital: ["Tokyo"],
    Flag_PNG: "https://flagcdn.com/w320/jp.png",
  },
  {
    Name: "Norfolk Island",
    Population: 2302,
    Region: "Oceania",
    Capital: ["Kingston"],
    Flag_PNG: "https://flagcdn.com/w320/nf.png",
  },
  {
    Name: "Central African Republic",
    Population: 4829764,
    Region: "Africa",
    Capital: ["Bangui"],
    Flag_PNG: "https://flagcdn.com/w320/cf.png",
  },
  {
    Name: "Macau",
    Population: 649342,
    Region: "Asia",
    Capital: undefined,
    Flag_PNG: "https://flagcdn.com/w320/mo.png",
  },
  {
    Name: "Syria",
    Population: 17500657,
    Region: "Asia",
    Capital: ["Damascus"],
    Flag_PNG: "https://flagcdn.com/w320/sy.png",
  },
  {
    Name: "Montserrat",
    Population: 4922,
    Region: "Americas",
    Capital: ["Plymouth"],
    Flag_PNG: "https://flagcdn.com/w320/ms.png",
  },
  {
    Name: "Spain",
    Population: 47351567,
    Region: "Europe",
    Capital: ["Madrid"],
    Flag_PNG: "https://flagcdn.com/w320/es.png",
  },
  {
    Name: "Gambia",
    Population: 2416664,
    Region: "Africa",
    Capital: ["Banjul"],
    Flag_PNG: "https://flagcdn.com/w320/gm.png",
  },
  {
    Name: "Turks and Caicos Islands",
    Population: 38718,
    Region: "Americas",
    Capital: ["Cockburn Town"],
    Flag_PNG: "https://flagcdn.com/w320/tc.png",
  },
  {
    Name: "French Southern and Antarctic Lands",
    Population: 400,
    Region: "Antarctic",
    Capital: ["Port-aux-Français"],
    Flag_PNG: "https://flagcdn.com/w320/tf.png",
  },
  {
    Name: "Saint Pierre and Miquelon",
    Population: 6069,
    Region: "Americas",
    Capital: ["Saint-Pierre"],
    Flag_PNG: "https://flagcdn.com/w320/pm.png",
  },
  {
    Name: "Nauru",
    Population: 10834,
    Region: "Oceania",
    Capital: ["Yaren"],
    Flag_PNG: "https://flagcdn.com/w320/nr.png",
  },
  {
    Name: "Faroe Islands",
    Population: 48865,
    Region: "Europe",
    Capital: ["Tórshavn"],
    Flag_PNG: "https://flagcdn.com/w320/fo.png",
  },
  {
    Name: "Saint Vincent and the Grenadines",
    Population: 110947,
    Region: "Americas",
    Capital: ["Kingstown"],
    Flag_PNG: "https://flagcdn.com/w320/vc.png",
  },
  {
    Name: "Canada",
    Population: 38005238,
    Region: "Americas",
    Capital: ["Ottawa"],
    Flag_PNG: "https://flagcdn.com/w320/ca.png",
  },
  {
    Name: "Egypt",
    Population: 102334403,
    Region: "Africa",
    Capital: ["Cairo"],
    Flag_PNG: "https://flagcdn.com/w320/eg.png",
  },
  {
    Name: "Papua New Guinea",
    Population: 8947027,
    Region: "Oceania",
    Capital: ["Port Moresby"],
    Flag_PNG: "https://flagcdn.com/w320/pg.png",
  },
  {
    Name: "Grenada",
    Population: 112519,
    Region: "Americas",
    Capital: ["St. George's"],
    Flag_PNG: "https://flagcdn.com/w320/gd.png",
  },
  {
    Name: "Czechia",
    Population: 10698896,
    Region: "Europe",
    Capital: ["Prague"],
    Flag_PNG: "https://flagcdn.com/w320/cz.png",
  },
  {
    Name: "Greece",
    Population: 10715549,
    Region: "Europe",
    Capital: ["Athens"],
    Flag_PNG: "https://flagcdn.com/w320/gr.png",
  },
  {
    Name: "Togo",
    Population: 8278737,
    Region: "Africa",
    Capital: ["Lomé"],
    Flag_PNG: "https://flagcdn.com/w320/tg.png",
  },
  {
    Name: "Australia",
    Population: 25687041,
    Region: "Oceania",
    Capital: ["Canberra"],
    Flag_PNG: "https://flagcdn.com/w320/au.png",
  },
  {
    Name: "Luxembourg",
    Population: 632275,
    Region: "Europe",
    Capital: ["Luxembourg"],
    Flag_PNG: "https://flagcdn.com/w320/lu.png",
  },
  {
    Name: "Niue",
    Population: 1470,
    Region: "Oceania",
    Capital: ["Alofi"],
    Flag_PNG: "https://flagcdn.com/w320/nu.png",
  },
  {
    Name: "Bahrain",
    Population: 1701583,
    Region: "Asia",
    Capital: ["Manama"],
    Flag_PNG: "https://flagcdn.com/w320/bh.png",
  },
  {
    Name: "Netherlands",
    Population: 16655799,
    Region: "Europe",
    Capital: ["Amsterdam"],
    Flag_PNG: "https://flagcdn.com/w320/nl.png",
  },
  {
    Name: "Uzbekistan",
    Population: 34232050,
    Region: "Asia",
    Capital: ["Tashkent"],
    Flag_PNG: "https://flagcdn.com/w320/uz.png",
  },
  {
    Name: "Hungary",
    Population: 9749763,
    Region: "Europe",
    Capital: ["Budapest"],
    Flag_PNG: "https://flagcdn.com/w320/hu.png",
  },
  {
    Name: "British Virgin Islands",
    Population: 30237,
    Region: "Americas",
    Capital: ["Road Town"],
    Flag_PNG: "https://flagcdn.com/w320/vg.png",
  },
  {
    Name: "Zambia",
    Population: 18383956,
    Region: "Africa",
    Capital: ["Lusaka"],
    Flag_PNG: "https://flagcdn.com/w320/zm.png",
  },
  {
    Name: "Thailand",
    Population: 69799978,
    Region: "Asia",
    Capital: ["Bangkok"],
    Flag_PNG: "https://flagcdn.com/w320/th.png",
  },
  {
    Name: "North Macedonia",
    Population: 2077132,
    Region: "Europe",
    Capital: ["Skopje"],
    Flag_PNG: "https://flagcdn.com/w320/mk.png",
  },
  {
    Name: "Saint Barthélemy",
    Population: 4255,
    Region: "Americas",
    Capital: ["Gustavia"],
    Flag_PNG: "https://flagcdn.com/w320/bl.png",
  },
  {
    Name: "Niger",
    Population: 24206636,
    Region: "Africa",
    Capital: ["Niamey"],
    Flag_PNG: "https://flagcdn.com/w320/ne.png",
  },
  {
    Name: "Somalia",
    Population: 15893219,
    Region: "Africa",
    Capital: ["Mogadishu"],
    Flag_PNG: "https://flagcdn.com/w320/so.png",
  },
  {
    Name: "Cameroon",
    Population: 26545864,
    Region: "Africa",
    Capital: ["Yaoundé"],
    Flag_PNG: "https://flagcdn.com/w320/cm.png",
  },
  {
    Name: "Russia",
    Population: 144104080,
    Region: "Europe",
    Capital: ["Moscow"],
    Flag_PNG: "https://flagcdn.com/w320/ru.png",
  },
  {
    Name: "Burundi",
    Population: 11890781,
    Region: "Africa",
    Capital: ["Gitega"],
    Flag_PNG: "https://flagcdn.com/w320/bi.png",
  },
];

const sufix = {
  MLT: "Malta",
  SWE: "Sweden",
  NCL: "New Caledonia",
  BFA: "Burkina Faso",
  BIH: "Bosnia and Herzegovina",
  JOR: "Jordan",
  PRI: "Puerto Rico",
  GRL: "Greenland",
  IRN: "Iran",
  LSO: "Lesotho",
  LVA: "Latvia",
  MDG: "Madagascar",
  CYP: "Cyprus",
  MUS: "Mauritius",
  SWZ: "Eswatini",
  SLB: "Solomon Islands",
  AUT: "Austria",
  VAT: "Vatican City",
  MWI: "Malawi",
  BWA: "Botswana",
  DJI: "Djibouti",
  COG: "Republic of the Congo",
  BRB: "Barbados",
  SXM: "Sint Maarten",
  RWA: "Rwanda",
  JEY: "Jersey",
  BVT: "Bouvet Island",
  YEM: "Yemen",
  BRA: "Brazil",
  DZA: "Algeria",
  KAZ: "Kazakhstan",
  MAF: "Saint Martin",
  CUW: "Curaçao",
  FJI: "Fiji",
  PAK: "Pakistan",
  SGS: "South Georgia",
  GEO: "Georgia",
  NAM: "Namibia",
  GNB: "Guinea-Bissau",
  NOR: "Norway",
  CXR: "Christmas Island",
  LIE: "Liechtenstein",
  IND: "India",
  FRA: "France",
  HKG: "Hong Kong",
  AIA: "Anguilla",
  COL: "Colombia",
  IRQ: "Iraq",
  MAR: "Morocco",
  LBY: "Libya",
  LCA: "Saint Lucia",
  MHL: "Marshall Islands",
  SLE: "Sierra Leone",
  COK: "Cook Islands",
  HRV: "Croatia",
  TKM: "Turkmenistan",
  BTN: "Bhutan",
  GBR: "United Kingdom",
  MCO: "Monaco",
  PLW: "Palau",
  GAB: "Gabon",
  DEU: "Germany",
  JPN: "Japan",
  NFK: "Norfolk Island",
  CAF: "Central African Republic",
  MAC: "Macau",
  SYR: "Syria",
  MSR: "Montserrat",
  ESP: "Spain",
  GMB: "Gambia",
  TCA: "Turks and Caicos Islands",
  ATF: "French Southern and Antarctic Lands",
  SPM: "Saint Pierre and Miquelon",
  NRU: "Nauru",
  FRO: "Faroe Islands",
  VCT: "Saint Vincent and the Grenadines",
  CAN: "Canada",
  EGY: "Egypt",
  PNG: "Papua New Guinea",
  GRD: "Grenada",
  CZE: "Czechia",
  GRC: "Greece",
  TGO: "Togo",
  AUS: "Australia",
  LUX: "Luxembourg",
  NIU: "Niue",
  BHR: "Bahrain",
  NLD: "Netherlands",
  UZB: "Uzbekistan",
  HUN: "Hungary",
  VGB: "British Virgin Islands",
  ZMB: "Zambia",
  THA: "Thailand",
  MKD: "North Macedonia",
  BLM: "Saint Barthélemy",
  NER: "Niger",
  SOM: "Somalia",
  CMR: "Cameroon",
  RUS: "Russia",
  BDI: "Burundi",
  PSE: "Palestine",
  MYS: "Malaysia",
  TZA: "Tanzania",
  KWT: "Kuwait",
  NGA: "Nigeria",
  CIV: "Ivory Coast",
  DNK: "Denmark",
  LTU: "Lithuania",
  CPV: "Cape Verde",
  AGO: "Angola",
  FIN: "Finland",
  PER: "Peru",
  PYF: "French Polynesia",
  PRT: "Portugal",
  GHA: "Ghana",
  MOZ: "Mozambique",
  KIR: "Kiribati",
  ATG: "Antigua and Barbuda",
  NZL: "New Zealand",
  PRY: "Paraguay",
  BLZ: "Belize",
  MNP: "Northern Mariana Islands",
  SVN: "Slovenia",
  ARM: "Armenia",
  ARE: "United Arab Emirates",
  ASM: "American Samoa",
  TLS: "Timor-Leste",
  BES: "Caribbean Netherlands",
  MNE: "Montenegro",
  POL: "Poland",
  PCN: "Pitcairn Islands",
  SVK: "Slovakia",
  BOL: "Bolivia",
  CHL: "Chile",
  ATA: "Antarctica",
  BGD: "Bangladesh",
  MEX: "Mexico",
  MNG: "Mongolia",
  IRL: "Ireland",
  CUB: "Cuba",
  GLP: "Guadeloupe",
  EST: "Estonia",
  SLV: "El Salvador",
  AFG: "Afghanistan",
  URY: "Uruguay",
  BLR: "Belarus",
  COD: "DR Congo",
  ESH: "Western Sahara",
  GIB: "Gibraltar",
  GUM: "Guam",
  AZE: "Azerbaijan",
  HTI: "Haiti",
  MLI: "Mali",
  DOM: "Dominican Republic",
  SGP: "Singapore",
  ARG: "Argentina",
  ISL: "Iceland",
  USA: "United States",
  JAM: "Jamaica",
  QAT: "Qatar",
  OMN: "Oman",
  ROU: "Romania",
  TTO: "Trinidad and Tobago",
  MDV: "Maldives",
  SSD: "South Sudan",
  ABW: "Aruba",
  FLK: "Falkland Islands",
  STP: "São Tomé and Príncipe",
  AND: "Andorra",
  PAN: "Panama",
  ALB: "Albania",
  HND: "Honduras",
  MYT: "Mayotte",
  GNQ: "Equatorial Guinea",
  HMD: "Heard Island and McDonald Islands",
  SEN: "Senegal",
  PRK: "North Korea",
  SMR: "San Marino",
  IOT: "British Indian Ocean Territory",
  KEN: "Kenya",
  LKA: "Sri Lanka",
  SHN: "Saint Helena, Ascension and Tristan da Cunha",
  LBN: "Lebanon",
  COM: "Comoros",
  MTQ: "Martinique",
  TWN: "Taiwan",
  CYM: "Cayman Islands",
  NIC: "Nicaragua",
  VIR: "United States Virgin Islands",
  TKL: "Tokelau",
  CHE: "Switzerland",
  BGR: "Bulgaria",
  TUV: "Tuvalu",
  LAO: "Laos",
  BRN: "Brunei",
  GGY: "Guernsey",
  NPL: "Nepal",
  CRI: "Costa Rica",
  KHM: "Cambodia",
  SAU: "Saudi Arabia",
  GIN: "Guinea",
  UMI: "United States Minor Outlying Islands",
  UNK: "Kosovo",
  FSM: "Micronesia",
  ISR: "Israel",
  ERI: "Eritrea",
  KOR: "South Korea",
  ALA: "Åland Islands",
  SRB: "Serbia",
  TON: "Tonga",
  VEN: "Venezuela",
  KGZ: "Kyrgyzstan",
  WLF: "Wallis and Futuna",
  SDN: "Sudan",
  BEL: "Belgium",
  UKR: "Ukraine",
  VUT: "Vanuatu",
  BMU: "Bermuda",
  TUN: "Tunisia",
  MRT: "Mauritania",
  IDN: "Indonesia",
  UGA: "Uganda",
  IMN: "Isle of Man",
  MMR: "Myanmar",
  CHN: "China",
  SJM: "Svalbard and Jan Mayen",
  SYC: "Seychelles",
  CCK: "Cocos (Keeling) Islands",
  ZWE: "Zimbabwe",
  BEN: "Benin",
  ETH: "Ethiopia",
  ZAF: "South Africa",
  GTM: "Guatemala",
  TCD: "Chad",
  LBR: "Liberia",
  GUF: "French Guiana",
  MDA: "Moldova",
  SUR: "Suriname",
  BHS: "Bahamas",
  VNM: "Vietnam",
  KNA: "Saint Kitts and Nevis",
  WSM: "Samoa",
  DMA: "Dominica",
  REU: "Réunion",
  ECU: "Ecuador",
  TJK: "Tajikistan",
  PHL: "Philippines",
  GUY: "Guyana",
  TUR: "Turkey",
  ITA: "Italy",
};

export { sampleCountries, sufix };
