const sufix = {
  MLT: "Malta",
  SWE: "Sweden",
  NCL: "New Caledonia",
  BFA: "Burkina Faso",
  BIH: "Bosnia and Herzegovina",
  JOR: "Jordan",
  PRI: "Puerto Rico",
  GRL: "Greenland",
  IRN: "Iran",
  LSO: "Lesotho",
  LVA: "Latvia",
  MDG: "Madagascar",
  CYP: "Cyprus",
  MUS: "Mauritius",
  SWZ: "Eswatini",
  SLB: "Solomon Islands",
  AUT: "Austria",
  VAT: "Vatican City",
  MWI: "Malawi",
  BWA: "Botswana",
  DJI: "Djibouti",
  COG: "Republic of the Congo",
  BRB: "Barbados",
  SXM: "Sint Maarten",
  RWA: "Rwanda",
  JEY: "Jersey",
  BVT: "Bouvet Island",
  YEM: "Yemen",
  BRA: "Brazil",
  DZA: "Algeria",
  KAZ: "Kazakhstan",
  MAF: "Saint Martin",
  CUW: "Curaçao",
  FJI: "Fiji",
  PAK: "Pakistan",
  SGS: "South Georgia",
  GEO: "Georgia",
  NAM: "Namibia",
  GNB: "Guinea-Bissau",
  NOR: "Norway",
  CXR: "Christmas Island",
  LIE: "Liechtenstein",
  IND: "India",
  FRA: "France",
  HKG: "Hong Kong",
  AIA: "Anguilla",
  COL: "Colombia",
  IRQ: "Iraq",
  MAR: "Morocco",
  LBY: "Libya",
  LCA: "Saint Lucia",
  MHL: "Marshall Islands",
  SLE: "Sierra Leone",
  COK: "Cook Islands",
  HRV: "Croatia",
  TKM: "Turkmenistan",
  BTN: "Bhutan",
  GBR: "United Kingdom",
  MCO: "Monaco",
  PLW: "Palau",
  GAB: "Gabon",
  DEU: "Germany",
  JPN: "Japan",
  NFK: "Norfolk Island",
  CAF: "Central African Republic",
  MAC: "Macau",
  SYR: "Syria",
  MSR: "Montserrat",
  ESP: "Spain",
  GMB: "Gambia",
  TCA: "Turks and Caicos Islands",
  ATF: "French Southern and Antarctic Lands",
  SPM: "Saint Pierre and Miquelon",
  NRU: "Nauru",
  FRO: "Faroe Islands",
  VCT: "Saint Vincent and the Grenadines",
  CAN: "Canada",
  EGY: "Egypt",
  PNG: "Papua New Guinea",
  GRD: "Grenada",
  CZE: "Czechia",
  GRC: "Greece",
  TGO: "Togo",
  AUS: "Australia",
  LUX: "Luxembourg",
  NIU: "Niue",
  BHR: "Bahrain",
  NLD: "Netherlands",
  UZB: "Uzbekistan",
  HUN: "Hungary",
  VGB: "British Virgin Islands",
  ZMB: "Zambia",
  THA: "Thailand",
  MKD: "North Macedonia",
  BLM: "Saint Barthélemy",
  NER: "Niger",
  SOM: "Somalia",
  CMR: "Cameroon",
  RUS: "Russia",
  BDI: "Burundi",
  PSE: "Palestine",
  MYS: "Malaysia",
  TZA: "Tanzania",
  KWT: "Kuwait",
  NGA: "Nigeria",
  CIV: "Ivory Coast",
  DNK: "Denmark",
  LTU: "Lithuania",
  CPV: "Cape Verde",
  AGO: "Angola",
  FIN: "Finland",
  PER: "Peru",
  PYF: "French Polynesia",
  PRT: "Portugal",
  GHA: "Ghana",
  MOZ: "Mozambique",
  KIR: "Kiribati",
  ATG: "Antigua and Barbuda",
  NZL: "New Zealand",
  PRY: "Paraguay",
  BLZ: "Belize",
  MNP: "Northern Mariana Islands",
  SVN: "Slovenia",
  ARM: "Armenia",
  ARE: "United Arab Emirates",
  ASM: "American Samoa",
  TLS: "Timor-Leste",
  BES: "Caribbean Netherlands",
  MNE: "Montenegro",
  POL: "Poland",
  PCN: "Pitcairn Islands",
  SVK: "Slovakia",
  BOL: "Bolivia",
  CHL: "Chile",
  ATA: "Antarctica",
  BGD: "Bangladesh",
  MEX: "Mexico",
  MNG: "Mongolia",
  IRL: "Ireland",
  CUB: "Cuba",
  GLP: "Guadeloupe",
  EST: "Estonia",
  SLV: "El Salvador",
  AFG: "Afghanistan",
  URY: "Uruguay",
  BLR: "Belarus",
  COD: "DR Congo",
  ESH: "Western Sahara",
  GIB: "Gibraltar",
  GUM: "Guam",
  AZE: "Azerbaijan",
  HTI: "Haiti",
  MLI: "Mali",
  DOM: "Dominican Republic",
  SGP: "Singapore",
  ARG: "Argentina",
  ISL: "Iceland",
  USA: "United States",
  JAM: "Jamaica",
  QAT: "Qatar",
  OMN: "Oman",
  ROU: "Romania",
  TTO: "Trinidad and Tobago",
  MDV: "Maldives",
  SSD: "South Sudan",
  ABW: "Aruba",
  FLK: "Falkland Islands",
  STP: "São Tomé and Príncipe",
  AND: "Andorra",
  PAN: "Panama",
  ALB: "Albania",
  HND: "Honduras",
  MYT: "Mayotte",
  GNQ: "Equatorial Guinea",
  HMD: "Heard Island and McDonald Islands",
  SEN: "Senegal",
  PRK: "North Korea",
  SMR: "San Marino",
  IOT: "British Indian Ocean Territory",
  KEN: "Kenya",
  LKA: "Sri Lanka",
  SHN: "Saint Helena, Ascension and Tristan da Cunha",
  LBN: "Lebanon",
  COM: "Comoros",
  MTQ: "Martinique",
  TWN: "Taiwan",
  CYM: "Cayman Islands",
  NIC: "Nicaragua",
  VIR: "United States Virgin Islands",
  TKL: "Tokelau",
  CHE: "Switzerland",
  BGR: "Bulgaria",
  TUV: "Tuvalu",
  LAO: "Laos",
  BRN: "Brunei",
  GGY: "Guernsey",
  NPL: "Nepal",
  CRI: "Costa Rica",
  KHM: "Cambodia",
  SAU: "Saudi Arabia",
  GIN: "Guinea",
  UMI: "United States Minor Outlying Islands",
  UNK: "Kosovo",
  FSM: "Micronesia",
  ISR: "Israel",
  ERI: "Eritrea",
  KOR: "South Korea",
  ALA: "Åland Islands",
  SRB: "Serbia",
  TON: "Tonga",
  VEN: "Venezuela",
  KGZ: "Kyrgyzstan",
  WLF: "Wallis and Futuna",
  SDN: "Sudan",
  BEL: "Belgium",
  UKR: "Ukraine",
  VUT: "Vanuatu",
  BMU: "Bermuda",
  TUN: "Tunisia",
  MRT: "Mauritania",
  IDN: "Indonesia",
  UGA: "Uganda",
  IMN: "Isle of Man",
  MMR: "Myanmar",
  CHN: "China",
  SJM: "Svalbard and Jan Mayen",
  SYC: "Seychelles",
  CCK: "Cocos (Keeling) Islands",
  ZWE: "Zimbabwe",
  BEN: "Benin",
  ETH: "Ethiopia",
  ZAF: "South Africa",
  GTM: "Guatemala",
  TCD: "Chad",
  LBR: "Liberia",
  GUF: "French Guiana",
  MDA: "Moldova",
  SUR: "Suriname",
  BHS: "Bahamas",
  VNM: "Vietnam",
  KNA: "Saint Kitts and Nevis",
  WSM: "Samoa",
  DMA: "Dominica",
  REU: "Réunion",
  ECU: "Ecuador",
  TJK: "Tajikistan",
  PHL: "Philippines",
  GUY: "Guyana",
  TUR: "Turkey",
  ITA: "Italy",
};

export { sufix };
